version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo "Branch = ${CODEBUILD_WEBHOOK_HEAD_REF}"

      - |
        if [ "${CODEBUILD_WEBHOOK_HEAD_REF}" = "refs/heads/main" ]; then
          echo "Deploy latest artifact"
          aws s3 sync output/ s3://${PREVIEW_BUCKET}/latest/ --delete

        elif [ "${CODEBUILD_WEBHOOK_HEAD_REF}" = "refs/heads/preview" ]; then
          echo "Deploy layout preview artifact"
          aws s3 sync output/ s3://${PREVIEW_BUCKET}/preview/ --delete

        else
          echo "Unsupported branch"
          exit 1
        fi

      - aws cloudfront create-invalidation \
          --distribution-id ${PREVIEW_DISTRIBUTION_ID} \
          --paths "/*"